### ISSUE TITLE
Error on installation

### ISSUE THREAD

**Issue by no-Seaweed** [lmb-freiburg/FreiPose-docker#1]
Hi,

Thanks for your great work and code. I got an error while executing` git clone https://github.com/lmb-freiburg/FreiPose-docker && cd FreiPose-docker && make`.

Here is the error I got

> Cloning into 'FreiPose-docker'...
> remote: Enumerating objects: 65, done.
> remote: Counting objects: 100% (65/65), done.
> remote: Compressing objects: 100% (46/46), done.
> remote: Total 65 (delta 28), reused 45 (delta 15), pack-reused 0
> Unpacking objects: 100% (65/65), done.
> Checking connectivity... done.
> docker build                                  \
>        -f Dockerfile                          \
>        -t docker-freipose                                  \
>        --build-arg machine_id=533de2d68c3c4618b2bf9160e7fac060 \
>        --build-arg uid=$UID                  \
>        --build-arg gid=$GROUPS               \
>        --build-arg username=$USER            \
> .
> unable to prepare context: unable to evaluate symlinks in Dockerfile path: lstat /home/yifu/FreiPose-docker/Dockerfile: no such file or directory
> Makefile:17: recipe for target 'docker-freipose' failed
> make: *** [docker-freipose] Error 1

Also, is it possible to install this repo without docker? I have no permission on using sudo in my school's cluster - I have to keep communicating them for permission to run dockers, and my Ubuntu computer's GPU is not good enough. Nvidia docker installation brought me a significant amount of troubles. 

Looking forward to your reply!

Best,
Shukai Fang

**Comment by zimmerm** [comment]
Hi,
thanks for your interest in our work. 
Because our paper is still in a preprint state, the actual code is not released yet, so installation is currently not possible.
This will change upon acceptance.

Cheers Chris

**Comment by no-Seaweed** [comment]
Thank you very much!
