### ISSUE TITLE
docker: Error response from daemon: Unknown runtime specified nvidia.

### ISSUE THREAD

**Issue by dukezacks** [lmb-freiburg/FreiPose-docker#4]
Hello, i am really impressed with your project i was trying to run it on my local machine and i got this error tried to solve it but still i cant.
Trying to do for my graduation research.
Please is there way you can advice how to go on with it?

Using Ubuntu 20.04 LTS 

![Screenshot from 2022-10-06 11-15-11](https://user-images.githubusercontent.com/106013071/194199224-cdd04ce7-5df6-48cc-af64-50b2f451adda.png)

**Comment by arturoptophys** [comment]
Hi,
this seems to be an issue with the docker/nvidia-docker installation. Please verify everything has been installed correctly.

```
sudo systemctl daemon-reload
sudo systemctl restart docker
```
might work as indicated here: https://github.com/NVIDIA/nvidia-docker/issues/838#issuecomment-439346505

Hope it helps,
Artur

**Comment by dukezacks** [comment]
Thank you this one solved but i couldn't run the predict i found an error please i have submitted the error if you have an idea how i can solve it i will appreciate Thank you.
